# fly.toml app configuration file generated for gpx-young-frost-228 on 2024-04-14T11:13:10-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpx'
primary_region = 'den'

[build]

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
